# Generated by Django 4.2.28 on 2026-02-13 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Customer's first name.", max_length=100)),
                ('last_name', models.CharField(help_text="Customer's last name.", max_length=100)),
                ('age', models.PositiveIntegerField(help_text="Customer's age (must be 18+).", validators=[django.core.validators.MinValueValidator(18)])),
                ('phone_number', models.BigIntegerField(db_index=True, help_text="Customer's phone number.")),
                ('monthly_salary', models.PositiveIntegerField(help_text="Customer's monthly income in INR.")),
                ('approved_limit', models.PositiveIntegerField(help_text='System-approved credit limit (36 * monthly_salary, rounded to nearest lakh).')),
                ('current_debt', models.FloatField(default=0.0, help_text="Customer's current outstanding debt.", validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='idx_customer_phone')],
            },
        ),
    ]
