# Generated by Django 4.2.28 on 2026-02-13 17:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='current_debt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Customer's current outstanding debt.", max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
