# Generated by Django 4.2.28 on 2026-02-13 16:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.FloatField(help_text='Total loan principal amount.', validators=[django.core.validators.MinValueValidator(0.01)])),
                ('tenure', models.PositiveIntegerField(help_text='Loan tenure in months.', validators=[django.core.validators.MinValueValidator(1)])),
                ('interest_rate', models.FloatField(help_text='Annual interest rate (percentage).', validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_installment', models.FloatField(help_text='Monthly EMI amount (calculated via compound interest).', validators=[django.core.validators.MinValueValidator(0)])),
                ('emis_paid_on_time', models.PositiveIntegerField(default=0, help_text='Number of EMIs paid on time.')),
                ('start_date', models.DateField(help_text='Loan start date.')),
                ('end_date', models.DateField(help_text='Loan end date.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the loan is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='The customer who owns this loan.', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customers.customer')),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'is_active'], name='idx_loan_customer_active')],
            },
        ),
    ]
